export const cround1 = [
    {
        "id": 1,
        "Name": "Kamaksha",
        "Block": "Alta G1",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Not an expert.\nBut competitive in whatever I do 😉\n",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 2,
        "Name": "Rakesh R",
        "Block": "Bella G02",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 3,
        "Name": "Dhivakar",
        "Block": "Alta 303",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 4,
        "Name": "Mohan Kumar P R",
        "Block": "Vivo 502",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "I am not pro, but I hold my own in every sport I play 😉💪",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 5,
        "Name": "Manas Ranjan Sur",
        "Block": "Bella 702",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 6,
        "Name": "Rupesh shewale",
        "Block": "Florido 501",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Cricket, volleyball, Water sports",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 7,
        "Name": "Indrasis biswas",
        "Block": "Unico 503",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Cricket, football, water sports",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 8,
        "Name": "Santosh",
        "Block": "Magnifica 804",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": "",
        "Table Tennis": "",
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 9,
        "Name": "Kapil Karamchandani",
        "Block": "Alta 201",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Good at Table Tennis\nBetter at Squash\nBest at Cricket",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 10,
        "Name": "Sudeepto roy",
        "Block": "Alta 603",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 11,
        "Name": "NAVYADEEP",
        "Block": "MAGNIFICA 303",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": "",
        "Table Tennis": "",
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 12,
        "Name": "Gregory Joseph",
        "Block": "Florida 102",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 13,
        "Name": "Anusha",
        "Block": "Buena 201",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 14,
        "Name": "Kritee Chopra",
        "Block": "Unico 805",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 15,
        "Name": "Samarveer Singh",
        "Block": "Alta 501",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at: Swimming\nBetter at: Badminton\nBest at: Basketball",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 16,
        "Name": "Harish",
        "Block": "Unico rpr",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 17,
        "Name": "Sureshnaik. Mg",
        "Block": "Fresco 202",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 18,
        "Name": "PARTHO",
        "Block": "Vivo-303",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Best : Badminton Swimming\nBetter : Carrom, Table Tennis\nGood : Lawn tennis, volleyball, water games",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 19,
        "Name": "Rahul Kunar",
        "Block": "Magnifica 405",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 20,
        "Name": "Rajeev Mandholia",
        "Block": "Unico - 806",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 21,
        "Name": "Manglam",
        "Block": "Unico 204",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 22,
        "Name": "Nina",
        "Block": "Florido 401",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Good at - water games  , Better at - table tennis, Best at - Badminton, throw ball.",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 23,
        "Name": "Khushboo",
        "Block": "Unico 506",
        "Gender": "Female",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 24,
        "Name": "Saroj",
        "Block": "Florido 301",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at Badminton (doubles and mixed doubles)\nBetter at Throwball",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 25,
        "Name": "Nitish Raj",
        "Block": "Magnifica, 603",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "I am a sports enthusiast with a passion for playing cricket, volleyball, table tennis, and various water sports.",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 26,
        "Name": "Soma Keshri",
        "Block": "Bella 802",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 27,
        "Name": "Debasish Mahato",
        "Block": "Unico 706",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 28,
        "Name": "Gayathri Velusamy",
        "Block": "VIVO 302",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 29,
        "Name": "Prannav",
        "Block": "Alta 605",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at snooker \nBetter at Volleyball \nBest at Cricket",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 30,
        "Name": "Rajendraa",
        "Block": "Florido 301",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at Badminton, Volleyball",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 31,
        "Name": "Jamsheer",
        "Block": "Buena 801",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "I play Cricket , Badminton and Snooker.",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 32,
        "Name": "Parul",
        "Block": "Florido106",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 33,
        "Name": "Kalpana",
        "Block": 201,
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 34,
        "Name": "Binay Bhusan Nanda",
        "Block": "Florido/204",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 35,
        "Name": "Hardeep",
        "Block": "Alta 505",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 36,
        "Name": "Manju",
        "Block": "Bella 202",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 37,
        "Name": "Minakshi Jha",
        "Block": "Magnifica 806",
        "Gender": "Female",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Enthusiastic learner with a passion for growth",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 38,
        "Name": "Ritu",
        "Block": "Fresco 604",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 39,
        "Name": "Wasim Akhtar",
        "Block": "Alta 704",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 40,
        "Name": "Anuj Hegde",
        "Block": "Magnifica 304",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at Carrom & Basketball. \nBetter at Snooker & Chess. \nBest at Badminton.",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 41,
        "Name": "Anusha Sanghvi",
        "Block": "Unico 205",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "While I’d call myself a beginner in the midst of all you experts, I’m proud to say I’m best at bringing sportsman spirit to the game.  Let’s make it fun! 🙂🏅\n",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 42,
        "Name": "Ashvini Brahmankar",
        "Block": "Magnifica 202",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 43,
        "Name": "Bishnu Panda",
        "Block": "Alta 401",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 44,
        "Name": "Ezra",
        "Block": "Magnifica 103",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Average in TT, badminton, snooker and athletics",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 45,
        "Name": "Harib Ansar",
        "Block": "604, Magnifica",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Good at Cricket, Carrom\nBetter at Table Tennis\nBest at Badminton",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 46,
        "Name": "Joe",
        "Block": "Vivo g3",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 47,
        "Name": "Jyotirmaya Pattanayak (Sanu)",
        "Block": "Vivo 602",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Cricket",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 48,
        "Name": "Manjunath",
        "Block": "FRESCO 203",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 49,
        "Name": "Mohan",
        "Block": "VIVO702",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Badminton/TableTennis - Beginner\nCricket - Intermediate",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 50,
        "Name": "Nandan",
        "Block": "Magnifica 505",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 51,
        "Name": "Nirmal Joseph",
        "Block": "Florido 401",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 1,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Good at : Table Tennis\nBetter at : Swimming & Water sports\nBest at : Chess",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 52,
        "Name": "Ritika",
        "Block": "Unico 204",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 1,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 53,
        "Name": "Sahil Brahmne",
        "Block": "Alta 504",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Cricket - Attacking batsman and part time off-spin bowler. Frequency of playing- every week. \nTable Tennis - District level in school. \nFrequency of playing- Twice a year.",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 54,
        "Name": "Tanveer Singh",
        "Block": "Alta 502",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "Good at - Badminton \nBetter at - Tennis\nBest at - Squash\nAlso good at Snooker and Carrom",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 55,
        "Name": "Abhishek Chaturvedi",
        "Block": "Buena 702",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 56,
        "Name": "Arka Misra",
        "Block": "Buena",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 57,
        "Name": "Arun",
        "Block": "Unico 402",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Best -Badminton, Carrom.\nOccasionally TT , cricket , basket ball",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 58,
        "Name": "Dinesh Singh",
        "Block": "Magnifica 506",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 1,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 59,
        "Name": "Kumari priyanka",
        "Block": "Unico 706",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 60,
        "Name": "Priti Kumari",
        "Block": "Florido 405",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 61,
        "Name": "Rajesh pal singh",
        "Block": "Bella 803",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 1,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 62,
        "Name": "Shadab",
        "Block": "Buena 302",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 1,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 63,
        "Name": "Sherin Mathew",
        "Block": "Vivo 603",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 64,
        "Name": "Shivaram Krishna",
        "Block": "Alta 403",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 1,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 65,
        "Name": "Shweta manjunath",
        "Block": "Fresco 203",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 66,
        "Name": "Sujatha Owk",
        "Block": "Magnifica 103",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 1,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 67,
        "Name": "Tejaswi Chandra",
        "Block": "Unico 106",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good: Cricket, Volleyball\nBest: Badminton",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 68,
        "Name": "Vartika Anand",
        "Block": "Magnifica 205",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 69,
        "Name": "Yogesh",
        "Block": "Fresco 701",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 70,
        "Name": "Anita Yadav",
        "Block": "Fresco-701",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 71,
        "Name": "Ashish kumar",
        "Block": "Florido 705",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 72,
        "Name": "Kavita Hegde",
        "Block": "Alta 404",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 73,
        "Name": "Mjay",
        "Block": "Florido-803",
        "Gender": "Male",
        "Cricket": 1,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 74,
        "Name": "Shamika pal",
        "Block": "Bella 803",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 75,
        "Name": "Sobin",
        "Block": "Bella 402",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 1,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Good at Cricket \nBetter at carroms \nBest at Vollyball",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 76,
        "Name": "Subhalaxmi Tripathy",
        "Block": "Florido 204",
        "Gender": "Female",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 1,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 77,
        "Name": "Suraj Sinha",
        "Block": "Magnifica 706",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "participating in Badminton singles and doubles",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 78,
        "Name": "Vidish Srivastava",
        "Block": "Magnifica 601",
        "Gender": "Male",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 0,
        "Handball": 0,
        "Kho Kho": 1,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 0,
        "Football": 0,
        "Badminton": 0,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    {
        "id": 79,
        "Name": "Zaira",
        "Block": "Magnifica 604",
        "Gender": "Female ",
        "Cricket": 0,
        "Volleyball": 0,
        "Throwball": 1,
        "Handball": 0,
        "Kho Kho": 0,
        "Water Polo": 0,
        "Water Throwball": 0,
        "Tug Of War": 0,
        "Basketball": 1,
        "Football": 0,
        "Badminton": 1,
        "Lawn Tennis": 0,
        "Table Tennis": 0,
        "basePrice": 0.5,
        "aboutMe": "Can play some team games",
        "Status": "",
        "Team": "",
        "SoldPrice": ""
    },
    
]